version: 2

updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "Dependencies"
    reviewers:
      - "usabilla/platform-java"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "CI"
    reviewers:
      - "usabilla/platform-java"
