name: dependency-license-report
on: [push]
jobs:
  dependency-license-report:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'
      - name: Build report overview of the vulnerabilities per dependency
        run: |
          ./gradlew generateLicenseReport
      - name: Upload dependency license report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: dependency-license-report.html
          path: ./build/reports/dependency-license/index.html
