name: documentation
on:
  push:
    branches:
      - 'main'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - run: pip install mkdocs pymdown-extensions
      - run: mkdocs gh-deploy --force
