name: publish
on:
  workflow_run:
    workflows: [ check ]
    types:
      - completed
    branches:
      - main
  push:
    branches:
      - main
    tags:
      - '[0-9]+.[0-9]+.[0-9]+$'
jobs:
  publish:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'
      - name: Setup
        run: |
          # due to https://github.com/google/google-java-format/blob/v1.12.0/README.md#jdk-16
          echo org.gradle.jvmargs=--add-exports jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED \
            --add-exports jdk.compiler/com.sun.tools.javac.file=ALL-UNNAMED \
            --add-exports jdk.compiler/com.sun.tools.javac.parser=ALL-UNNAMED \
            --add-exports jdk.compiler/com.sun.tools.javac.tree=ALL-UNNAMED \
            --add-exports jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED >> ./gradle.properties
      - name: Publish artifact
        run: |
          ./gradlew publish -PprojVersion=${{ github.ref_name }} -PgithubRepositoryUsername=${{ secrets.PACKAGE_REGISTRY_GITHUB_USER }} -PgithubRepositoryPassword=${{ secrets.PACKAGE_REGISTRY_GITHUB_TOKEN }} 
