name: publish
on:
  workflow_run:
    workflows: [ check ]
    types:
      - completed
    branches:
      - 'main'
  create:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+$'
    branches:
      - 'main'
jobs:
  publish:
    if: startsWith(github.ref, 'refs/tags')
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'
      - name: Publish artifact
        env:
          PGP_KEY: ${{secrets.OSS_GPG_KEY}}
          PGP_PSW: ${{secrets.OSS_GPG_PASSPHRASE}}
        run: |
          ./gradlew publish -PprojVersion=${{ github.ref_name }} -PgithubRepositoryUsername=${{ secrets.PACKAGE_REGISTRY_GITHUB_USER }} -PgithubRepositoryPassword=${{ secrets.PACKAGE_REGISTRY_GITHUB_TOKEN }} -PsignJar
