name: publish
on:
  workflow_run:
    workflows: [ check ]
    types:
      - completed
    branches: [ main ]
    tags:
      - /^\d+\.\d+\.\d+$/
jobs:
  publish:
    runs-on: ubuntu-20.04
    steps:
      - name: Publish artifact
        run: |
          ./gradlew publish --project-prop projVersion="${{ github.ref_name }}" -PgitHubRepositoryUsername=${{ secrets.PACKAGE_REGISTRY_GITHUB_USER }} -PgitHubRepositoryPassword=${{ secrets.PACKAGE_REGISTRY_GITHUB_TOKEN }}
