name: update-gradle-wrapper
on:
  schedule:
    - cron: "0 0 * * *"
jobs:
  update-gradle-wrapper:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Update Gradle Wrapper
        uses: gradle-update/update-gradle-wrapper-action@v1
        with:
          team-reviewers: kahpp/mainteiners
          labels: Dependencies
